[package]
name = "graphene-std"
version = "0.1.0"
edition = "2021"
description = "Graphene standard library"
authors = ["Dennis Kobert <dennis@kobert.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rust_analyzer = ["ide", "ide_db"]
caching = ["storage-map", "lock_api", "parking_lot"]
derive = ["graph-proc-macros"]
memoization = ["once_cell"]
default = ["derive", "memoization"]


[dependencies]
graphene-core = {path = "../gcore"}
dyn-any = {path = "../dyn-any", features = ["derive"]}
graph-proc-macros = {path = "../proc-macro", optional = true}
once_cell = {version= "1.10", optional = true}
ide = { version = "*", package = "ra_ap_ide", optional = true }
ide_db = { version = "*", package = "ra_ap_ide_db" , optional = true }
storage-map = { version = "*", optional = true }
lock_api = { version= "*", optional = true }
parking_lot = { version = "*", optional = true }
